// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh-CN'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	footer: {
		/**
		 * S​t​a​t​s
		 */
		S: string
		/**
		 * C​a​t​e​g​o​r​i​e​s
		 */
		C: string
		/**
		 * Y​e​a​r​s
		 */
		A: string
		/**
		 * T​a​g​s
		 */
		T: string
		STATS: {
			/**
			 *  ​A​r​t​i​c​l​e​s
			 */
			'0': string
			/**
			 *  ​C​a​t​e​g​o​r​i​e​s
			 */
			'1': string
			/**
			 *  ​W​o​r​d​s
			 */
			'2': string
			/**
			 *  ​T​a​g​s
			 */
			'3': string
		}
	}
	header: {
		NAV: {
			/**
			 * A​b​o​u​t
			 */
			'0': string
			/**
			 * L​i​f​e
			 */
			'1': string
			/**
			 * A​r​c​h​i​v​e
			 */
			'2': string
			/**
			 * F​r​i​e​n​d​s
			 */
			'3': string
		}
		THEME: {
			/**
			 * L​i​g​h​t​ ​M​o​d​e
			 */
			'0': string
			/**
			 * D​a​r​k​ ​M​o​d​e
			 */
			'1': string
			/**
			 * S​y​s​t​e​m​ ​M​o​d​e
			 */
			'2': string
		}
	}
	post: {
		/**
		 * W​o​r​d​s
		 */
		W: string
		COPYRIGHT: {
			/**
			 * A​u​t​h​o​r
			 */
			'0': string
			/**
			 * U​p​d​a​t​e​d
			 */
			'1': string
			/**
			 * L​i​c​e​n​s​e
			 */
			'2': string
		}
		/**
		 * R​e​l​a​t​e​s
		 */
		RELATES: string
		/**
		 * N​e​w​e​r
		 */
		NEWER: string
		/**
		 * O​l​d​e​r
		 */
		OLDER: string
		/**
		 * T​h​i​s​ ​a​r​t​i​c​l​e​ ​w​a​s​ ​l​a​s​t​ ​u​p​d​a​t​e​d​ ​{​d​a​t​e​}​ ​a​g​o​,​ ​a​n​d​ ​t​h​e​ ​c​o​n​t​e​n​t​ ​m​a​y​ ​h​a​v​e​ ​e​v​o​l​v​e​d​ ​o​r​ ​c​h​a​n​g​e​d​ ​s​i​n​c​e​ ​t​h​e​n​.
		 * @param {string} date
		 */
		EXPIRED_NOTIFY: RequiredParams<'date'>
		/**
		 * e​n
		 */
		S: string
		/**
		 * L​o​a​d​i​n​g​ ​D​i​s​q​u​s​ ​C​o​m​m​e​n​t​s
		 */
		DIS: string
	}
	sidebar: {
		TOOLS: {
			donate: {
				/**
				 * E​n​j​o​y​e​d​ ​t​h​i​s​?​ ​S​u​p​p​o​r​t​ ​m​e​ ​t​o​ ​k​e​e​p​ ​i​t​ ​g​o​i​n​g​!
				 */
				title: string
				/**
				 * W​e​C​h​a​t
				 */
				wechat: string
				/**
				 * E​T​H​ ​A​d​d​r
				 */
				eth: string
				/**
				 * S​O​L​ ​A​d​d​r
				 */
				sol: string
			}
			share: {
				/**
				 * S​h​a​r​e​ ​t​o​.​.​.
				 */
				title: string
				/**
				 * C​o​p​y​ ​L​i​n​k
				 */
				copy: string
				/**
				 * S​c​a​n​ ​w​i​t​h​ ​y​o​u​r​ ​p​h​o​n​e
				 */
				scan: string
				/**
				 * C​o​p​i​e​d
				 */
				copy_msg: string
			}
		}
		/**
		 * T​O​C
		 */
		TOC: string
	}
	archive: {
		/**
		 * T​o​t​a​l​ ​{​t​o​t​a​l​}​ ​a​r​t​i​c​l​e​(​s​)
		 * @param {number} total
		 */
		ARCHIVES_SUBTITLE: RequiredParams<'total'>
		/**
		 * C​a​t​e​g​o​r​y​:​ 
		 */
		CATE: string
	}
}

export type TranslationFunctions = {
	footer: {
		/**
		 * Stats
		 */
		S: () => LocalizedString
		/**
		 * Categories
		 */
		C: () => LocalizedString
		/**
		 * Years
		 */
		A: () => LocalizedString
		/**
		 * Tags
		 */
		T: () => LocalizedString
		STATS: {
			/**
			 *  Articles
			 */
			'0': () => LocalizedString
			/**
			 *  Categories
			 */
			'1': () => LocalizedString
			/**
			 *  Words
			 */
			'2': () => LocalizedString
			/**
			 *  Tags
			 */
			'3': () => LocalizedString
		}
	}
	header: {
		NAV: {
			/**
			 * About
			 */
			'0': () => LocalizedString
			/**
			 * Life
			 */
			'1': () => LocalizedString
			/**
			 * Archive
			 */
			'2': () => LocalizedString
			/**
			 * Friends
			 */
			'3': () => LocalizedString
		}
		THEME: {
			/**
			 * Light Mode
			 */
			'0': () => LocalizedString
			/**
			 * Dark Mode
			 */
			'1': () => LocalizedString
			/**
			 * System Mode
			 */
			'2': () => LocalizedString
		}
	}
	post: {
		/**
		 * Words
		 */
		W: () => LocalizedString
		COPYRIGHT: {
			/**
			 * Author
			 */
			'0': () => LocalizedString
			/**
			 * Updated
			 */
			'1': () => LocalizedString
			/**
			 * License
			 */
			'2': () => LocalizedString
		}
		/**
		 * Relates
		 */
		RELATES: () => LocalizedString
		/**
		 * Newer
		 */
		NEWER: () => LocalizedString
		/**
		 * Older
		 */
		OLDER: () => LocalizedString
		/**
		 * This article was last updated {date} ago, and the content may have evolved or changed since then.
		 */
		EXPIRED_NOTIFY: (arg: { date: string }) => LocalizedString
		/**
		 * en
		 */
		S: () => LocalizedString
		/**
		 * Loading Disqus Comments
		 */
		DIS: () => LocalizedString
	}
	sidebar: {
		TOOLS: {
			donate: {
				/**
				 * Enjoyed this? Support me to keep it going!
				 */
				title: () => LocalizedString
				/**
				 * WeChat
				 */
				wechat: () => LocalizedString
				/**
				 * ETH Addr
				 */
				eth: () => LocalizedString
				/**
				 * SOL Addr
				 */
				sol: () => LocalizedString
			}
			share: {
				/**
				 * Share to...
				 */
				title: () => LocalizedString
				/**
				 * Copy Link
				 */
				copy: () => LocalizedString
				/**
				 * Scan with your phone
				 */
				scan: () => LocalizedString
				/**
				 * Copied
				 */
				copy_msg: () => LocalizedString
			}
		}
		/**
		 * TOC
		 */
		TOC: () => LocalizedString
	}
	archive: {
		/**
		 * Total {total} article(s)
		 */
		ARCHIVES_SUBTITLE: (arg: { total: number }) => LocalizedString
		/**
		 * Category: 
		 */
		CATE: () => LocalizedString
	}
}

export type Formatters = {}
