// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zh-CN'

export type Locales =
	| 'en'
	| 'zh-CN'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	footer: {
		/**
		 * 统​计
		 */
		S: string
		/**
		 * 分​类
		 */
		C: string
		/**
		 * 归​档
		 */
		A: string
		/**
		 * 标​签
		 */
		T: string
		STATS: {
			/**
			 *  ​文​章
			 */
			'0': string
			/**
			 *  ​分​类
			 */
			'1': string
			/**
			 *  ​千​字
			 */
			'2': string
			/**
			 *  ​标​签
			 */
			'3': string
		}
	}
	header: {
		NAV: {
			/**
			 * 关​于
			 */
			'0': string
			/**
			 * 生​活
			 */
			'1': string
			/**
			 * 归​档
			 */
			'2': string
			/**
			 * 友​链
			 */
			'3': string
		}
		THEME: {
			/**
			 * 浅​色​模​式
			 */
			'0': string
			/**
			 * 深​色​模​式
			 */
			'1': string
			/**
			 * 跟​随​系​统
			 */
			'2': string
		}
	}
	post: {
		/**
		 * 字
		 */
		W: string
		COPYRIGHT: {
			/**
			 * 作​者
			 */
			'0': string
			/**
			 * 更​新​于
			 */
			'1': string
			/**
			 * 许​可​协​议
			 */
			'2': string
		}
		/**
		 * 相​关​文​章
		 */
		RELATES: string
		/**
		 * 本​文​最​近​一​次​更​新​于​ ​{​d​a​t​e​}​前​，​其​中​的​内​容​很​可​能​已​经​有​所​发​展​或​是​发​生​改​变​。
		 * @param {string} date
		 */
		EXPIRED_NOTIFY: RequiredParams<'date'>
		/**
		 * 共​计​ ​{​t​o​t​a​l​}​ ​篇​文​章
		 * @param {number} total
		 */
		ARCHIVES_SUBTITLE: RequiredParams<'total'>
		/**
		 * z​h​-​C​N
		 */
		S: string
		/**
		 * 正​在​加​载​ ​D​i​s​q​u​s​ ​评​论
		 */
		DIS: string
	}
	sidebar: {
		TOOLS: {
			/**
			 * 喜​欢​这​篇​文​章​？​可​以​考​虑​赞​赏​支​持​一​下​作​者
			 */
			donate: string
			share: {
				/**
				 * 分​享​到​.​.​.
				 */
				title: string
				/**
				 * 复​制​链​接
				 */
				copy: string
				/**
				 * 手​机​扫​一​扫
				 */
				scan: string
				/**
				 * 已​复​制
				 */
				copy_msg: string
			}
		}
		/**
		 * 目​录
		 */
		TOC: string
	}
	archive: {
		/**
		 * 共​计​ ​{​t​o​t​a​l​}​ ​篇​文​章
		 * @param {number} total
		 */
		SUBTITLE: RequiredParams<'total'>
		/**
		 * 分​类​：
		 */
		CATE: string
	}
}

export type TranslationFunctions = {
	footer: {
		/**
		 * 统计
		 */
		S: () => LocalizedString
		/**
		 * 分类
		 */
		C: () => LocalizedString
		/**
		 * 归档
		 */
		A: () => LocalizedString
		/**
		 * 标签
		 */
		T: () => LocalizedString
		STATS: {
			/**
			 *  文章
			 */
			'0': () => LocalizedString
			/**
			 *  分类
			 */
			'1': () => LocalizedString
			/**
			 *  千字
			 */
			'2': () => LocalizedString
			/**
			 *  标签
			 */
			'3': () => LocalizedString
		}
	}
	header: {
		NAV: {
			/**
			 * 关于
			 */
			'0': () => LocalizedString
			/**
			 * 生活
			 */
			'1': () => LocalizedString
			/**
			 * 归档
			 */
			'2': () => LocalizedString
			/**
			 * 友链
			 */
			'3': () => LocalizedString
		}
		THEME: {
			/**
			 * 浅色模式
			 */
			'0': () => LocalizedString
			/**
			 * 深色模式
			 */
			'1': () => LocalizedString
			/**
			 * 跟随系统
			 */
			'2': () => LocalizedString
		}
	}
	post: {
		/**
		 * 字
		 */
		W: () => LocalizedString
		COPYRIGHT: {
			/**
			 * 作者
			 */
			'0': () => LocalizedString
			/**
			 * 更新于
			 */
			'1': () => LocalizedString
			/**
			 * 许可协议
			 */
			'2': () => LocalizedString
		}
		/**
		 * 相关文章
		 */
		RELATES: () => LocalizedString
		/**
		 * 本文最近一次更新于 {date}前，其中的内容很可能已经有所发展或是发生改变。
		 */
		EXPIRED_NOTIFY: (arg: { date: string }) => LocalizedString
		/**
		 * 共计 {total} 篇文章
		 */
		ARCHIVES_SUBTITLE: (arg: { total: number }) => LocalizedString
		/**
		 * zh-CN
		 */
		S: () => LocalizedString
		/**
		 * 正在加载 Disqus 评论
		 */
		DIS: () => LocalizedString
	}
	sidebar: {
		TOOLS: {
			/**
			 * 喜欢这篇文章？可以考虑赞赏支持一下作者
			 */
			donate: () => LocalizedString
			share: {
				/**
				 * 分享到...
				 */
				title: () => LocalizedString
				/**
				 * 复制链接
				 */
				copy: () => LocalizedString
				/**
				 * 手机扫一扫
				 */
				scan: () => LocalizedString
				/**
				 * 已复制
				 */
				copy_msg: () => LocalizedString
			}
		}
		/**
		 * 目录
		 */
		TOC: () => LocalizedString
	}
	archive: {
		/**
		 * 共计 {total} 篇文章
		 */
		SUBTITLE: (arg: { total: number }) => LocalizedString
		/**
		 * 分类：
		 */
		CATE: () => LocalizedString
	}
}

export type Formatters = {}
